### ISSUE TITLE
Data Quantification Process

### ISSUE THREAD

**Issue by cpdaniels** [edsp2016/ITIMA_Zafrin_Harrison#2]
I don't know Python but am interested in the basics of how this is done. Might be useful in the readme to walk us through the process (not a blow by blow, but just a general idea). 

Do you have a sense yet of how you're going to model the data?

**Comment by bombsandbottles** [comment]
Added some more stuff on the opening readme about the data.  I've linked my Python code in the readme as well, I'm afraid to get into too much detail on the feature extraction as I could get carried away and it's not 100% relevant to the project.
