### ISSUE TITLE
example file doesn't work with existing data files

### ISSUE THREAD

**Issue by ybergner** [edsp2016/ITIMA_Zafrin_Harrison#4]
The readLines example fails when pointed to the data in the path "../Data/Ariana\ Grande\ -\ One\ Last\ Time/" because there are unexpected characters ("[") and non-comma-separated lines. I think the local example you had worked though. You should update the Data with the new versions

**Comment by bombsandbottles** [comment]
Yeah the data files currently uploaded are broken and not what was tested in class, will get around to fixing all this stuff Wednesday!
