### ISSUE TITLE
Midterm Project Comments

### ISSUE THREAD

**Issue by danielomm314** [edsp2016/ITIMA_Zafrin_Harrison#5]
Is your goal to determine what the value of 'x' is in your analysis of loudness? 

Does the Main Element mean whatever track currently has the solo? 

In the visualizations you create how do you plan to communicate their meaning/interpretation to non-musical experts?

Can you break songs down into intro, verse, chorus, bridge, etc.?

**Comment by bombsandbottles** [comment]
That's correct, the main goal for this project is now to determine the value of 'x', where 'x' is the "loudness" level of the lead element against the rest of the instrumentation.  The lead element is determined by its label.  So "lead vocal" would be an example.  There is only ever really 1 lead element at any given time.
